# Aftman toolchain configuration for RvrseUI
# https://github.com/LPGhatguy/aftman

[tools]
stylua = "JohnnyMorganz/StyLua@0.20.0"
selene = "Kampfkarren/selene@0.27.1"
rojo = "rojo-rbx/rojo@7.4.1"
wally = "UpliftGames/wally@0.3.2"
