# Aftman toolchain configuration for RvrseUI
# https://github.com/LPGhatguy/aftman

[tools]
# Lua code formatter
roblox/stylua = "0.20.0"

# Lua linter
kampfkarren/selene = "0.27.1"

# Roblox project builder
rojo-rbx/rojo = "7.4.1"

# Roblox package manager
upliftgames/wally = "0.3.2"
