name: luau-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev curl unzip lua5.1
          if ! command -v cargo >/dev/null 2>&1; then
            sudo apt-get install -y cargo
          fi
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          cargo install stylua --locked --force
          cargo install selene --locked --force
          cargo install rojo --locked --force
          cargo install wally-cli --locked --force

      - name: Stylua
        run: stylua --check .

      - name: Selene
        run: selene .

      - name: Rojo build
        run: rojo build default.project.json --output build/RvrseUI.rbxlx

      - name: Wally install
        run: wally install

      - name: TestEZ
        run: lua tools/testez.lua
