name: luau-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          set -euxo pipefail

          # Install Lua runtime for TestEZ
          sudo apt-get update
          sudo apt-get install -y lua5.1

          # Install Aftman (the preferred toolchain manager for Roblox projects)
          curl -sSfL https://github.com/LPGhatguy/aftman/releases/download/v0.2.7/aftman-v0.2.7-linux.zip -o aftman.zip
          unzip -o aftman.zip
          chmod +x aftman
          sudo mv aftman /usr/local/bin/aftman

          # Add Aftman bin directory to PATH
          mkdir -p "$HOME/.aftman/bin"
          echo "$HOME/.aftman/bin" >> $GITHUB_PATH

      - name: Install toolchain via Aftman
        run: |
          set -euxo pipefail

          # Trust all tools (CI environment, no user prompts)
          aftman trust roblox/stylua
          aftman trust kampfkarren/selene
          aftman trust rojo-rbx/rojo
          aftman trust upliftgames/wally

          # Install all tools from aftman.toml
          aftman install --no-trust-check

          # Verify installations
          echo "✅ Installed tools:"
          stylua --version
          selene --version
          rojo --version
          wally --version

      - name: Stylua
        run: stylua --check .

      - name: Selene
        run: selene .

      - name: Rojo build
        run: rojo build default.project.json --output build/RvrseUI.rbxlx

      - name: Wally install
        run: wally install

      - name: TestEZ
        run: lua tools/testez.lua
