name: luau-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build toolchain
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev curl unzip lua5.1 cargo
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          if ! command -v stylua >/dev/null 2>&1; then
            cargo install stylua --locked
          fi
          if ! command -v selene >/dev/null 2>&1; then
            cargo install selene --locked
          fi
          if ! command -v rojo >/dev/null 2>&1; then
            cargo install rojo --locked
          fi
          if ! command -v wally >/dev/null 2>&1; then
            tmpdir=$(mktemp -d)
            # Pin to v0.3.2 release (known working version)
            WALLY_VERSION="v0.3.2"
            WALLY_URL="https://github.com/UpliftGames/wally/releases/download/${WALLY_VERSION}/wally-${WALLY_VERSION}-linux-x86_64.zip"

            echo "Installing Wally ${WALLY_VERSION}..."
            if curl -sSfL "$WALLY_URL" -o "$tmpdir/wally.zip"; then
              unzip -o "$tmpdir/wally.zip" -d "$tmpdir"
            else
              echo "Failed to download Wally ${WALLY_VERSION}" >&2
              exit 1
            fi

            if [ -f "$tmpdir/wally" ]; then
              sudo mv "$tmpdir/wally" /usr/local/bin/wally
              sudo chmod +x /usr/local/bin/wally
              echo "Wally ${WALLY_VERSION} installed successfully"
            else
              echo "Wally binary not found after extraction" >&2
              ls -la "$tmpdir"
              exit 1
            fi

            rm -rf "$tmpdir"
          fi

      - name: Stylua
        run: stylua --check .

      - name: Selene
        run: selene .

      - name: Rojo build
        run: rojo build default.project.json --output build/RvrseUI.rbxlx

      - name: Wally install
        run: wally install

      - name: TestEZ
        run: lua tools/testez.lua
